### PR TITLE
Use non-ABI jars for kotlin compilation.

### LINKED ISSUE #40: Importing Kotlin jars
I'm getting build errors trying to access some functions from third-party jars. I'm not sure if this is directly related to `rules_kotlin` or a more general problem with how bazel handles Kotlin code in jars. I haven't tried importing Kotlin code into Java (with bazel). 

I've made a small example gist: https://gist.github.com/jmmk/2aa367c00548dd34e0a8637462493bd2. I tried all 3 of `java_deps`, `jars`, and `deps` as I'm not 100% clear on the difference between these. Using `java_deps` gets the farthest in the build, but still fails. Note that I'm using `rules_maven` for the dependencies, but experienced the same issue with [bazel-deps](https://github.com/johnynek/bazel-deps).

Example build output of `bazel build main_deploy.jar`:

```sh
ERROR: /Users/jmmk/Desktop/bazel-kotlin/BUILD:3:1: Compiling 1 Kotlin source files to main_kt.jar failed (Exit 1).
/private/var/tmp/_bazel_jmmk/b4a1d5dca7a3dfe59337df9230eb1872/bazel-sandbox/5737601483947724481/execroot/__main__/App.kt:4:18: error: unresolved reference: launch
import tornadofx.launch
                 ^
/private/var/tmp/_bazel_jmmk/b4a1d5dca7a3dfe59337df9230eb1872/bazel-sandbox/5737601483947724481/execroot/__main__/App.kt:11:33: error: unresolved reference: launch
fun main(args: Array<String>) = launch<MyApp>(args)
                                ^
Target //:main_deploy.jar failed to build
```

Another library I've had fail is https://github.com/FasterXML/jackson-module-kotlin/blob/master/src/main/kotlin/com/fasterxml/jackson/module/kotlin/Extensions.kt#L15, where I got `unresolved reference: jacksonObjectMapper()`.

### PR DESCRIPTION
**Pull request by pcj**
Also adds two new kotlin_compile attributes:

1. verbose: for printing debugging info
2. args: for passing arbitrary args to compilation

Adds new test from @jmmk re: tornadofx

Fixes #40

### CODE REVIEW

**Comment by pcj** [comment]
@jmmk can you take a look at this PR and try it on your end?

```python
git_repository(
    name = "org_pubref_rules_kotlin",
    remote = "https://github.com/pubref/rules_kotlin.git",
    commit = "4f780394cb3d4f1bb18b72179c1b2865e533c9bf", 
)
```

**Comment by pcj** [comment]
@iirina Can you check this?  For kotlin compilation we need to assemble a list of jars to pass to kotlinc.  I think I should probably be using the set of transitive full jars, is `full_compile_jars` the transitive set?

**Comment by jmmk** [comment]
@pcj Confirmed that using `rules_kotlin` on commit `4f780394cb3d4f1bb18b72179c1b2865e533c9bf` (and adding `"-jvm-target", "1.8",` to `compile_args`) builds the tornadofx example.

---

However, I tested [Jackson Kotlin module](https://github.com/FasterXML/jackson-module-kotlin) and it still failed. See gist here: https://gist.github.com/jmmk/842fac837b7af8ebefde85e476f9002d

**Comment by pcj** [comment]
Took a look at the gist and added a comment.

**Comment by pcj** [comment]
OK, I can't remember exactly why I was removing kotlin-stdlib.jar and kotlin-reflect.jar from classpath... Some experiment perhaps that I failed to remove.

**Comment by jmmk** [comment]
@pcj the Jackson example works after the latest commit

**Comment by iirina** [comment]
@pcj 

>  For kotlin compilation we need to assemble a list of jars to pass to kotlinc. I think I should probably be using the set of transitive full jars, is full_compile_jars the transitive set?

`full_compile_jars` only gives you the direct jars, not the ones collected transitively. The transitive ones are not exposed right now on the provider, but they can be exposed easily if you need them.

**Comment by pcj** [comment]
@iirina Yes we do need the transitive jars exposed.  See https://github.com/pubref/rules_kotlin/issues/47

**Comment by iirina** [comment]
Can you open a GH issue on bazel and assign it to me please?

**Comment by pcj** [comment]
I created the issue https://github.com/bazelbuild/bazel/issues/4297 (but do not have permission to make assignments).

Thanks!

**Pull request merged**
